# Generated by Django 5.2.6 on 2025-09-24 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_alter_images_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='ie_origem',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
