# Generated by Django 5.2.6 on 2025-09-24 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_images_ie_origem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='ie_origem',
            field=models.CharField(blank=True, choices=[('PRF', 'PERFIL'), ('PFF', 'PERFIL_FUNDO'), ('PST', 'POSTAGEM')], max_length=255, null=True),
        ),
    ]
