version: '3.9'

services:
  orknew-api:
    build: .
    container_name: orknew-api
    ports:
      - "8012:8000"
    env_file:
      - .env

#  dropping-proxy:
#    image: nginx:latest
#    ports:
#      - "80:80"
#    volumes:
#      - ./nginx.conf:/etc/nginx/nginx.conf:ro
#      - /staticfiles:/static:ro
#    depends_on:
#      - dropping-api

#  postgres:
#    image: postgres:16
#    ports:
#      - '5435:5432'
#    environment:
#      - POSTGRES_USER=${DB_USER}
#      - POSTGRES_PASSWORD=${DB_PASSWORD}
#      - POSTGRES_DB=${DB_NAME}
#    volumes:
#      - polls_pg_data:/var/lib/postgresql/data
#
#volumes:
#  polls_pg_data:
