# Generated by Django 5.2.6 on 2025-09-24 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nm_descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('dt_created_at', models.DateField(auto_now_add=True)),
                ('dt_updated_at', models.DateField(blank=True, null=True)),
                ('dt_deleted_at', models.DateField(blank=True, null=True)),
                ('nm_user_create', models.CharField(blank=True, max_length=100, null=True)),
                ('nm_user_update', models.CharField(blank=True, max_length=100, null=True)),
                ('nm_user_delete', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
